### ISSUE TITLE
<--DefinesType relationship is missing for Type entities

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology#5]
It is likely to be a problem in the model library because printout at loadAll() at the server side shows that the JSON object supplied to the model library contains it.

**Comment by mhelvens** [comment]
Note: I initially missed this issue because it was not given a milestone.

**Comment by mhelvens** [comment]
Issue moved to [open-physiology/open-physiology-model #4](https://github.com/open-physiology/open-physiology-model/issues/4) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mhelvens** [comment]
Also, wrong repo.

Apparently I can move them using ZenHub, but it doesn't carry over any meta-data.
