### ISSUE TITLE
GET /canonicalTrees returns trees that miss relationships

### ISSUE THREAD

**Issue by albatros13** [open-physiology/open-physiology#6]
Probably the same error in model library as with Type

**Comment by mhelvens** [comment]
Note: This issue was created in the wrong repository. Should have gone to open-physiology/open-physiology-model.

**Comment by mhelvens** [comment]
Issue moved to [open-physiology/open-physiology-model #5](https://github.com/open-physiology/open-physiology-model/issues/5) via [**ZenHub**](https://www.zenhub.com/)
